Server: Check for invalid floats in all packets
SpadesX/SpadesX pull request #64
Opened 2023-06-19 22:42 UTC by utf-4096

Fixes:
- Server freezing when grenades with invalid floats as position or velocity are sent
- Player disappearing in VOXLAP/BetterSpades when an orientation with invalid floats is sent

Changes proposed in this pull request:
- Check all packets that have floats for nan/inf and drop them
- Slightly cleanup some related code along the way

2023-06-19 23:06 UTC, DavidCo113 commented
I think that invisibility with non-finite floats affects OpenSpades clients too, unlike invisibility with {0,0,0} orientation.

2023-06-19 23:07 UTC, DavidCo113 commented
Also haven't been able to reproduce server freeze with non-finite grenades more than once, however it does crash OpenSpades clients.

2023-06-19 23:08 UTC, DavidCo113 commented
And having non-finite orientation alone does appear to crash Voxlap clients, although at seemingly random times.

2023-06-19 23:16 UTC, Haxk20 requested changes
Except the requested change do we not receive floats anywhere else from packets ?

2023-06-19 23:16 UTC, Haxk20 commented on Source/Server/Packets/OrientationData.c
> +    if (!valid_vec3f((vector3f_t){x, y, z})) {
Instead of dynamic conversion create a vector and convert the packet to vector usage.

2023-06-19 23:18 UTC, Haxk20 commented
Also did davidco have direct contribution on the code ? Such as they wrote part of it or etc ? Suggestions are not counted as coauthored by. They should just be given credit but no special tag.

2023-06-19 23:23 UTC, utf-4096 commented
> Except the requested change do we not receive floats anywhere else from packets ?

No, only in the packets I've fixed.



> Also did davidco have direct contribution on the code ? Such as they wrote part of it or etc ? Suggestions are not counted as coauthored by. They should just be given credit but no special tag.

My bad, misunderstood its use.

2023-06-20 00:00 UTC, Haxk20 approved these changes

2023-06-20 00:00 UTC, merged